let &t_ti.="\e[1 q"
let &t_SI.="\e[5 q"
let &t_EI.="\e[1 q"
let &t_te.="\e[0 q"
set number
set nolist
set formatoptions+=1
set lbr
set mouse=c
set anti enc=utf-8
set expandtab
set tabstop=4
set shiftwidth=4
set background=dark
set ruler
set autochdir
set backupdir-=.
set backupdir+=/tmp//
set dir=/tmp//
set showcmd
syntax on
inoremap fd <Esc>
nnoremap <SPACE> <Nop>
vnoremap <SPACE> <Nop>
map <SPACE> <Leader>
nnoremap n nzz
nnoremap <Leader>wj <C-W><C-J>
nnoremap <Leader>wk <C-W><C-K>
nnoremap <Leader>wl <C-W><C-L>
nnoremap <Leader>wh <C-W><C-H>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
nnoremap <D-d> <C-d>
nnoremap <D-u> <C-u>
vnoremap <D-d> <C-d>
vnoremap <D-u> <C-u>
nnoremap <D-j> <C-W><C-j>
nnoremap <D-k> <C-W><C-k>
nnoremap <D-l> <C-W><C-l>
nnoremap <D-h> <C-W><C-h>
filetype indent plugin on
autocmd Filetype gitcommit setlocal spell textwidth=72
autocmd Filetype svn setlocal spell textwidth=72
autocmd Filetype markdown setlocal spell
